<a href="https://colab.research.google.com/github/Akihide0517/publicPrograms/blob/main/%E6%A5%BD%E6%9B%B2%E7%94%9F%E6%88%90AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pythonで演奏

In [ ]:
# ライブラリのインストール
!pip install mingus
!apt install -y fluidsynth


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 1.9 MB/s eta 0:00:00
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  fluid-soundfont-gm libevdev2 libfluidsynth3 libgudev-1.0-0 libinput-bin libinput10
  libinstpatch-1.0-2 libmd4c0 libmtdev1 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5
  libqt5svg5 libqt5widgets5 libwacom-bin libwacom-common libwacom9 libxcb-icccm4 libxcb-image0
  libxcb-keysyms1 libxcb-render-util0 libxcb-util1 libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1
  libxkbcommon-x11-0 qsynth qt5-gtk-platformtheme qttranslations5-l10n timgm6mb-soundfont
Suggested packages:
  fluid-soundfont-gs qt5-image-formats-plugins qtwayland5 jackd
The following NEW packages will be installed:
  fluid-soundfont-gm fluidsynth libevdev2 libfluidsynth3 libgudev-1.0-0 libinput-bin libinput10
  libinstpatch-1.0-2 libmd4c0 libmtdev1 libqt5core5a libqt5dbus5 libqt5gui5 libqt5netw

In [ ]:
# ライブラリのインポート
from mingus.containers import Note, Track, Composition, Bar
from mingus.midi import midi_file_out
import subprocess


In [ ]:
# 音源を作成する関数
def generate_song(song_notes, notes_lengths, filename, meter):
  # トラック作成
  track = Track()

  # 新しい小節を作成して各音符を追加
  bar = Bar()
  bar.meter = meter  #曲の拍子
  for note, length in zip(song_notes, notes_lengths):
    if note == "rest":
      if not bar.place_rest(length):
        track.add_bar(bar)
        bar = Bar()
        bar.meter = meter
        bar.place_rest(length)
    else:
      if not bar.place_notes(note, length):
        # 小節をトラックに追加
        track.add_bar(bar)
        bar = Bar()
        bar.meter = meter
        bar.place_notes(note, length)

  # 最後の小節を追加
  track.add_bar(bar)

  # 楽曲にトラックを追加
  composition = Composition()
  composition.add_track(track)

  # MIDIファイルを生成
  midi_filename = filename + ".mid"
  midi_file_out.write_Composition(midi_filename, composition)

  # MIDIをWAVに変換
  wav_filename = filename + ".wav"
  subprocess.run(["fluidsynth", "-ni", "FluidR3_GM.sf2", midi_filename, "-F", wav_filename, "-r", "44100"])


In [ ]:
# 曲のタイトル
title = "かたつむり"

# メロディを定義
song_notes = ["G-4", "rest", "G-4", "G-4", "E-4", "C-4", "rest", "C-4", "C-4", "D-4", "E-4", "rest", "E-4", "D-4", "C-4", "D-4", "rest",
              "E-4", "rest", "F-4", "G-4", "A-4", "G-4", "rest", "G-4", "G-4", "E-4", "D-4", "rest", "D-4", "C-4", "D-4", "E-4", "rest",
              "G-4", "C-5", "C-5", "G-4", "E-4", "G-4", "G-4", "E-4", "C-4", "E-4", "E-4", "rest", "D-4", "C-4", "rest"]
notes_lengths = [8, 16, 16, 8, 8, 8, 16, 16, 8, 8, 8, 16, 16, 8, 8, 4, 4,
                 8, 16, 16, 8, 8, 8, 16, 16, 8, 8, 8, 16, 16, 8, 8, 4, 4,
                 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 16, 16, 4, 4]

# 音源生成
generate_song(song_notes, notes_lengths, title, meter=(2, 4))


In [ ]:
# 曲のタイトル
title = "夕焼け小焼け"

# メロディを定義
song_notes = ["G-4", "G-4", "A-4", "G-4", "G-4", "G-4", "E-4", "C-4", "C-4", "D-4", "E-4", "D-4", "rest",
              "E-4", "E-4", "G-4", "A-4", "C-5", "C-5", "A-4", "G-4", "G-4", "A-4", "G-4", "C-5", "rest",
              "C-5", "rest", "D-5", "C-5", "A-4", "C-5", "C-5", "G-4", "G-4", "A-4", "G-4", "A-4", "G-4", "E-4", "rest",
              "G-4", "E-4", "D-4", "C-4", "D-4", "D-4", "C-4", "D-4", "E-4", "G-4", "A-4", "G-4", "C-5"]
notes_lengths = [2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2,
                 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2,
                 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2,
                 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1]

# 音源生成
generate_song(song_notes, notes_lengths, title, meter=(4, 4))


In [ ]:
# 曲のタイトル
title = "一月一日"

# メロディを定義
song_notes = ["A-4", "B-4", "A-4", "F#-4", "rest", "E-4", "D-4", "D-4", "E-4", "E-4", "A-4", "rest", "G-4", "F#-4", "rest",
              "A-4", "B-4", "A-4", "F#-4","rest", "E-4", "D-4", "D-4", "E-4", "E-4", "F#-4", "rest", "E-4", "D-4", "rest",
              "D-5", "D-5", "D-5", "B-4", "D-5", "A-4", "A-4", "B-4", "B-4", "A-4", "rest", "G-4", "F#-4", "rest",
              "A-4", "B-4", "A-4", "D-5", "rest", "B-4", "A-4", "G-4", "F#-4", "A-4", "G-4", "rest", "E-4", "D-4", "rest"]
notes_lengths = [2, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 8, 8, 2, 2,
                 2, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 8, 8, 2, 2,
                 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 8, 8, 2, 2,
                 2, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 8, 8, 2, 2]

# 音源生成
generate_song(song_notes, notes_lengths, title, meter=(4, 4))


In [ ]:
# 曲のタイトル
title = "シャボン玉"

# メロディを定義
song_notes = ["A-3", "D-4", "D-4", "D-4", "E-4", "F#-4", "A-4", "A-4", "rest", "B-4", "G-4", "D-5", "B-4", "A-4", "B-4", "A-4", "rest",
              "F#-4", "F#-4", "E-4", "D-4", "E-4", "A-4", "A-4", "rest", "B-4", "B-4", "A-4", "D-4", "F#-4", "E-4", "D-4", "rest",
              "D-5", "rest", "D-5", "D-5", "D-5", "D-5", "B-4", "A-4", "rest", "D-4", "D-4", "E-4", "F#-4", "A-4", "F#-4", "E-4", "D-4", "rest"]
notes_lengths = [4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 4]
# 音源生成
generate_song(song_notes, notes_lengths, title, meter=(4, 4))


In [ ]:
# 曲のタイトル
title = "春が来た"

# メロディを定義
song_notes = ["G-4", "E-4", "F-4", "G-4", "A-4", "G-4", "E-4", "F-4", "G-4", "C-5", "A-4", "G-4", "E-4", "rest", "C-4", "D-4", "rest",
              "G-4", "A-4", "G-4", "E-4", "G-4", "C-5", "D-5", "C-5", "A-4", "C-5", "G-4", "E-5", "D-5", "rest", "G-4", "C-5", "rest"]
notes_lengths = [4, 8, 8, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 8, 8, 2, 2,
                 4, 8, 8, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 8, 8, 2, 2]

# 音源生成
generate_song(song_notes, notes_lengths, title, meter=(4, 4))


In [ ]:
import os
import shutil
from google.colab import files

# ダウンロードするファイルの拡張子
target_extension = '.wav'
# ファイルを一時的に保存するディレクトリを作成
dir = 'download_folder'
os.makedirs(dir, exist_ok=True)

# カレントディレクトリ内のファイルをリストアップ
for filename in os.listdir('.'):
    if filename.endswith(target_extension):
        shutil.copy(filename, os.path.join(dir, filename))

# ダウンロードのためのzipファイルを作成
shutil.make_archive('music_files', 'zip', dir)

# zipファイルをダウンロード
files.download('music_files.zip')

# 一時ディレクトリを削除
shutil.rmtree(dir)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

楽曲作成

In [ ]:
# ライブラリのインポート
import pretty_midi
import numpy as np
import os
from google.colab import files


In [ ]:
# MIDIファイルをアップロード
uploaded = files.upload()


Saving 一月一日.mid to 一月一日 (1).mid
Saving 春が来た.mid to 春が来た.mid
Saving 夕焼け小焼け.mid to 夕焼け小焼け (1).mid


In [ ]:
# データセット保持リスト
datasets = []

# アップロードされた各MIDIファイルに対して処理
for midi_file in uploaded.keys():
    if midi_file.endswith('.mid') or midi_file.endswith('.midi'):
        # MIDIデータの読み込み
        midi_data = pretty_midi.PrettyMIDI(midi_file)

        all_notes = []

        for instrument in midi_data.instruments:
            for note in instrument.notes:
                # 各音の開始時間、終了時間、音の高さを学習の特徴量として使用
                all_notes.append([note.start, note.end, note.pitch])

        # 数値化
        all_notes_array = np.array(all_notes)

        # 正規化
        max_values = np.max(all_notes_array, axis=0)
        min_values = np.min(all_notes_array, axis=0)
        normalized_all_notes = (all_notes_array - min_values) / (max_values - min_values)

        # 系列データの作成
        sequence_length = 10
        X = []
        y = []
        for i in range(len(normalized_all_notes) - sequence_length):
            X.append(normalized_all_notes[i:i + sequence_length])
            y.append(normalized_all_notes[i + sequence_length])
        X = np.array(X)
        y = np.array(y)

        # この楽曲のデータセットをリストに追加
        datasets.append((X, y))


学習

In [ ]:
# ライブラリのインポート
from keras.models import Sequential
from keras.layers import LSTM, Dense
import random


In [ ]:
# LSTMモデルの設計
model = Sequential()
# 入力形状：10タイムステップ、3特徴量
model.add(LSTM(128, input_shape=(10, 3)))
# 全結合層の追加
model.add(Dense(3))


In [ ]:
# モデルのコンパイル
model.compile(optimizer='adam', loss="mse")


In [ ]:
# エポック数
epochs = 50

# 学習ループ
for epoch in range(epochs):
    X_batch, y_batch = random.choice(datasets)
    model.train_on_batch(X_batch, y_batch)


In [ ]:
# データセットの一部を入力として使用
input_data = X_batch[0].reshape(1, 10, 3)

# ここでは、30音の楽曲を生成。song_lengthの値を変更してお好きな長さの曲を生成してください。
song_length = 30
generated_music = []
for i in range(song_length):
    predicted_note = model.predict(input_data)
    generated_music.append(predicted_note[0])
    input_data = np.append(input_data[:, 1:, :], predicted_note.reshape(1, 1, 3), axis=1)


1/1 [==============================] - 0s 21ms/step


In [ ]:
generated_music


[array([0.20910014, 0.17087892, 0.3317767 ], dtype=float32),
 array([0.2189401 , 0.18771055, 0.32581693], dtype=float32),
 array([0.2327206 , 0.20690548, 0.3251103 ], dtype=float32),
 array([0.24818784, 0.22773057, 0.32504174], dtype=float32),
 array([0.2658984 , 0.24851441, 0.3294295 ], dtype=float32),
 array([0.284245  , 0.26926345, 0.33455986], dtype=float32),
 array([0.30294424, 0.2898463 , 0.3399933 ], dtype=float32),
 array([0.32301763, 0.3096011 , 0.34915584], dtype=float32),
 array([0.344501  , 0.32831383, 0.3626462 ], dtype=float32),
 array([0.36564228, 0.34695053, 0.37505016], dtype=float32),
 array([0.38590422, 0.36610475, 0.38418335], dtype=float32),
 array([0.40452898, 0.38530073, 0.38973513], dtype=float32),
 array([0.42368767, 0.4047677 , 0.39541075], dtype=float32),
 array([0.44303423, 0.42427593, 0.40096876], dtype=float32),
 array([0.46241063, 0.4437196 , 0.4063269 ], dtype=float32),
 array([0.4817103 , 0.4630587 , 0.41136897], dtype=float32),
 array([0.5009047 , 0.48

In [ ]:
# 逆正規化
denormalized_music = generated_music * (max_values - min_values) + min_values

# MIDIオブジェクトの作成
generated_midi = pretty_midi.PrettyMIDI()

# instrumentを作成
instrument_program = pretty_midi.instrument_name_to_program('Acoustic Grand Piano')
instrument = pretty_midi.Instrument(program=instrument_program)

# 開始時間
current_time = 0.0
for note_array in denormalized_music:
    start, end, pitch = note_array
    time_interval = end - start

    start = current_time
    end = current_time + time_interval
    note = pretty_midi.Note(velocity=127, pitch=int(pitch), start=start, end=end)
    instrument.notes.append(note)

    current_time += time_interval

# MIDIファイルへの書き出し
generated_midi.instruments.append(instrument)
output_file_path = "generated_music.mid"
generated_midi.write(output_file_path)


In [ ]:
files.download('generated_music.mid')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# ライブラリのインストール
!apt-get install -y lilypond


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  dvisvgm fonts-droid-fallback fonts-lmodern fonts-noto-mono fonts-urw-base35 ghostscript
  libfontenc1 libgs9 libgs9-common libidn12 libijs-0.35 libjbig2dec0 libkpathsea6 libptexenc1
  libsynctex2 libteckit0 libtexlua53 libtexluajit2 libwoff1 libzzip-0-13 lilypond-data
  lilypond-fonts lmodern poppler-data t1utils tex-common texlive-base texlive-binaries
  texlive-latex-base xfonts-encodings xfonts-utils
Suggested packages:
  fonts-noto fonts-freefont-otf | fonts-freefont-ttf fonts-texgyre ghostscript-x lilypond-doc
  python3-lxml poppler-utils fonts-japanese-mincho | fonts-ipafont-mincho fonts-japanese-gothic
  | fonts-ipafont-gothic fonts-arphic-ukai fonts-arphic-uming fonts-nanum debhelper perl-tk xpdf
  | pdf-viewer xzdec texlive-latex-base-doc
The following NEW packages will be installed:
  dvisvgm fonts-droid-fallback fonts-lmodern

In [ ]:
# MIDIファイルをMusicXMLへ変換
from music21 import *

# MIDIファイルを読み込み
midi_path = "generated_music.mid"
midi_stream = converter.parse(midi_path)

# メタデータ（タイトルや作曲者など）を設定
midi_metadata = metadata.Metadata()
midi_metadata.title = "Generated Music"
midi_metadata.composer = "yoshida"
midi_stream.metadata = midi_metadata

# MusicXMLとして保存
musicxml_path = "generated_music.xml"
midi_stream.write('musicxml', fp=musicxml_path)


PosixPath('/content/generated_music.xml')

In [ ]:
!musicxml2ly generated_music.xml -o generated_music.ly


musicxml2ly: Reading MusicXML from generated_music.xml ...
musicxml2ly: warning: overfull measure? Expected: 49/24, Difference: -1/24
  In: <measure implicit=no number=2>

  In: <part id=Pcfff7041e65354d9c05e9e6a9b4f7c90>

  In: <score-partwise version=4.0>

musicxml2ly: warning: overfull measure? Expected: 193/24, Difference: -1/24
  In: <measure implicit=no number=8>

  In: <part id=Pcfff7041e65354d9c05e9e6a9b4f7c90>

  In: <score-partwise version=4.0>

musicxml2ly: warning: overfull measure? Expected: 625/48, Difference: -1/48
  In: <measure implicit=no number=13>

  In: <part id=Pcfff7041e65354d9c05e9e6a9b4f7c90>

  In: <score-partwise version=4.0>

musicxml2ly: Converting to LilyPond expressions...
musicxml2ly: warning: Negative skip -1/24 (from position 49/24 to 2)
musicxml2ly: warning: Negative skip -1/24 (from position 49/24 to 2)
musicxml2ly: warning: Negative skip -1/24 (from position 55/24 to 9/4)
musicxml2ly: warning: Negative skip -1/24 (from position 55/24 to 9/4)
musicxm

In [ ]:
!lilypond -dbackend=eps -dno-gs-load-fonts -dinclude-eps-fonts --png generated_music.ly


GNU LilyPond 2.22.1
Processing `generated_music.ly'
Parsing...
Interpreting music...
generated_music.ly:29:15: warning: barcheck failed at: 1/24
    e4.. e8 ~ 
              | % 3
generated_music.ly:72:12: warning: unterminated tie
    r2. f4 
           ~ | % 4
generated_music.ly:30:35: warning: barcheck failed at: 17/48
    e4 ~ e16 r2*2/3 f4.. r4*11/12 
                                  | % 4
generated_music.ly:33:19: warning: unterminated tie
    r4*2/3 f2*2/3 
                  ~ r2*17/24 f16 ~ | % 5
generated_music.ly:33:36: warning: barcheck failed at: 25/48
    r4*2/3 f2*2/3 ~ r2*17/24 f16 ~ 
                                   | % 5
generated_music.ly:40:5: warning: barcheck failed at: 9/16
    
    | % 9
generated_music.ly:74:25: warning: unterminated tie
    r2 r8. fis4 ~ fis16 
                        ~ s1*4 \bar "|."
generated_music.ly:48:49: warning: barcheck failed at: 3/4
    fis8. r4*2/3 fis2*2/3 ~ fis4*11/12 r2*13/24 
                                                | %

In [ ]:
# 楽譜のダウンロード
files.download('generated_music.png')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>